# Generated by Django 4.0.4 on 2022-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_stripecard_stripe_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='brand',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stripecard',
            name='exp_month',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stripecard',
            name='exp_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stripecard',
            name='last4',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
