# Generated by Django 4.0.4 on 2022-06-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_stripecard_brand_stripecard_exp_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecard',
            name='stripe_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='orders.stripecustomer'),
        ),
    ]
