# Generated by Django 4.0.4 on 2022-06-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_stripecard_stripe_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(14, 'Pending'), (1, 'Complete'), (2, 'Incomplete')], default=0),
        ),
    ]
