# Generated by Django 4.0.4 on 2022-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Incomplete')], default=0),
        ),
    ]
