# Generated by Django 4.0.4 on 2022-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='stores/'),
        ),
    ]
