# Generated by Django 4.0.4 on 2022-05-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_store_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('normal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('processor_owner', models.CharField(max_length=255)),
                ('cores_number', models.IntegerField(default=1)),
                ('processor_technology', models.IntegerField(default=None, null=True)),
                ('memory_capacity', models.IntegerField(default=None, null=True)),
                ('memory_type', models.CharField(max_length=255)),
                ('hdd_type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.store')),
            ],
        ),
    ]
