# Generated by Django 4.0.4 on 2022-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hdd_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory_type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
