# Generated by Django 4.0.4 on 2022-06-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
